spring:
  application:
    name:

server:
  port: 8080

openai:
  api-key: ${OPENAI_API_KEY:}
  chat-model: gpt-4o-mini
  embedding-model: text-embedding-3-small

rag:
  chunk:
  size: 800 # tokens/words depending on splitter
  overlap: 80 # overlap between chunks
  retrieval:
  top-k: 5
  min-score: 0.60